clean2 <- function(text) {
    require(stringr)
    text <- tolower(text)
    text <- gsub("lol", " ", text)
    # separate hyphenated words
    text <- gsub("[-]", " ", text)
    text <- gsub("[^'[:^punct:]]"," ", text, perl = TRUE)
    text <- gsub("[[:digit:]]","", text)
    text <- gsub(" +", " ", text)
    text <- gsub("(f|ht)tp(s?)://(.*)[.][a-z]+", "", text)
    text <- gsub("[`´]","'", text)
    text <- gsub("'re", " are", text)
    text <- gsub("'ve", " have", text)
    text <- gsub("he's ", "he is ", text)
    text <- gsub("^he's ", "he is ", text)
    text <- gsub("she's ", "she is ", text)
    text <- gsub("^she's ", "she is ", text)
    text <- gsub("it's ", "it is ", text)
    text <- gsub("^it's ", "it is ", text)
    text <- gsub("'ll", " will", text)
    text <- gsub("'d", " would", text)
    text <- gsub("'m", " am", text)
    text <- gsub(" m ", " am ", text)
    text <- gsub(" i ", " I ", text)
    text <- gsub("^i ", "I ", text)
    text <- gsub("can't", "cannot", text)
    text <- gsub("doesn't", "does not", text)
    text <- gsub("don't", "do not", text)
    text <- gsub("didn't", "did not", text)
    text <- gsub("won't", "will not", text)
    text <- gsub("that's ", "that is ", text)
    text <- gsub("^that's ", "that is ", text)
    text <- gsub(" rt ", " ", text)
    text <- gsub("syoure", "so you are", text)
    text <- gsub("yoyou", "you", text)

    text <- gsub("[^a-zA-Z]", " ", text)
    text <- gsub(" t ", "", text)
    text <- gsub(" s ", "", text)
    #text <- str_split(text, " ")

    # text <- str_replace_all(text,"#\\S+", " ")
    # text <- str_replace_all(text,"(f|ht)tp(s?)://(.*)[.][a-z]+", " ")
    # text <- str_replace_all(text,"\\.+", ". ")
    # text <- str_replace_all(text,"\\?|\\!", ". ")
    # if (!unigram) {
    #     text <- str_replace_all(text,"[^a-zA-Z\\.\\,\\']", " ")
    # } else {
    #     text <- str_replace_all(text,"[^a-zA-Z\\.\\']", " ")
    # }
    # text <- str_replace_all(text,"\\ ' |\\' |\\ '", " ")
    # text <- str_replace_all(text,"[\\s]+", " ")
    # 
    # text <- str_replace_all(text," s ", "'s ")
    # text <- str_replace_all(text," t ", "'t ")
    # text <- str_replace_all(text," u ", " you ")
    # text <- str_replace_all(text," $|\\.$|\\. $", "")
    # text <- str_replace_all(text,"\\. ", ".")
    # text <- str_replace_all(text,"\\, ", ",")
    #text <- str_split(text, "\\.|\\,")
    text <- unlist(text)
    return(text)
}